server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: admin
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  liquibase:
    enabled: true
    drop-first: false
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: public
  kafka:
    bootstrap-servers: localhost:9092

topic:
  service-request: service-request
  service-request-group-id: service-request